/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugas_pv;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;


/**
 *
 * @author User
 */
public class Guru extends javax.swing.JFrame {

     public Connection con;
    public Statement st;
    public ResultSet res;
    public DefaultTableModel model=new DefaultTableModel();
    private String tgl,sek,valied,namapegawai; 
    
    public Guru(String namapegawai) {
        initComponents();
        this.namapegawai=namapegawai;
        ImageIcon ico = new ImageIcon("src/tugas_pv/img/iconpni.png");
        setIconImage(ico.getImage());
        model.addColumn("ID");
         model.addColumn("Nama");
         model.addColumn("sekolah");
         model.addColumn("kontak");
         model.addColumn("Email");
         model.addColumn("Valid");
         tbl.setModel(model);
Nsekolah();      
AutoCompleteDecorator.decorate(sekolah);
table();
                        tgl();
                        jam();
                       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        kontak = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        delet = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        cari = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        sekolah = new javax.swing.JComboBox<>();
        v = new javax.swing.JRadioButton();
        nv = new javax.swing.JRadioButton();
        idguru = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PT Pelatos Nasional Indonesia - Marketing");
        setLocation(new java.awt.Point(220, 54));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Della Respira", 0, 11)); // NOI18N
        jLabel2.setText("Nama");

        jLabel3.setFont(new java.awt.Font("Della Respira", 0, 11)); // NOI18N
        jLabel3.setText("Sekolah");

        jLabel4.setFont(new java.awt.Font("Della Respira", 0, 11)); // NOI18N
        jLabel4.setText("Kontak");

        jLabel5.setFont(new java.awt.Font("Della Respira", 0, 11)); // NOI18N
        jLabel5.setText("Email");

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_pv/img/savee.png"))); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_pv/img/edite.png"))); // NOI18N
        jButton2.setText("Edit");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_pv/img/clear.png"))); // NOI18N
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        delet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_pv/img/delet.png"))); // NOI18N
        delet.setText("Delet");
        delet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletActionPerformed(evt);
            }
        });

        tbl.setAutoCreateRowSorter(true);
        tbl.setForeground(new java.awt.Color(102, 102, 102));
        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode Guru", "Nama", "Sekolah", "Kontak", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl.setGridColor(new java.awt.Color(255, 255, 255));
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_pv/img/cari.png"))); // NOI18N
        jButton5.setText("Cari");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel11.setText(" ");

        jLabel12.setText(" ");

        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Della Respira", 0, 14)); // NOI18N
        jLabel13.setText("           ");

        jLabel14.setFont(new java.awt.Font("REVOLUTION", 1, 24)); // NOI18N
        jLabel14.setText("guRU");

        sekolah.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Piliih Sekolah" }));
        sekolah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sekolahActionPerformed(evt);
            }
        });

        v.setText("Valied");
        v.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vActionPerformed(evt);
            }
        });

        nv.setText("Tidak Valied");
        nv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel13)
                        .addGap(94, 94, 94)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addGap(19, 19, 19))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nama)
                            .addComponent(kontak, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                            .addComponent(sekolah, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(109, 109, 109)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jButton1)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButton3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(delet))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jButton5))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel5)
                                                    .addGap(34, 34, 34)
                                                    .addComponent(email)
                                                    .addGap(69, 69, 69))))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(jLabel14)
                                        .addGap(135, 135, 135)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(170, 170, 170)
                                .addComponent(v)
                                .addGap(46, 46, 46)
                                .addComponent(nv)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(idguru, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel14))
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idguru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(v)
                            .addComponent(nv))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(delet)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(sekolah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(kontak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
simpan();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
//bersih();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void deletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletActionPerformed
    hapus();
    }//GEN-LAST:event_deletActionPerformed

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
int i = tbl.getSelectedRow();
//DefaultTableModel model=new DefaultTableModel();
if(i>-1){
   idguru.setText(model.getValueAt(i,0).toString());
   nama.setText(model.getValueAt(i,1).toString());
   sekolah.setSelectedItem(model.getValueAt(i,2).toString());
   kontak.setText(model.getValueAt(i,3).toString());
   email.setText(model.getValueAt(i,4).toString());
   valied =(model.getValueAt(i,5).toString());
   
}
if(valied.equals("Valied")){v.setSelected(true);nv.setSelected(false);}
           else{nv.setSelected(true);v.setSelected(false);
        }

    }//GEN-LAST:event_tblMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      edit();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      cari();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void sekolahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sekolahActionPerformed
         sek = (String) sekolah.getSelectedItem();
    }//GEN-LAST:event_sekolahActionPerformed

    private void vActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vActionPerformed
        valied="Valied";
    }//GEN-LAST:event_vActionPerformed

    private void nvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nvActionPerformed
       valied="Tidak Valied";
    }//GEN-LAST:event_nvActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Guru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
         /*catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(pengadaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
         } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(pengadaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
         } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(pengadaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
         } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(pengadaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
         }*/
         //</editor-fold>
         /*catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(pengadaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
         } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(pengadaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
         } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(pengadaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
         } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(pengadaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
         }*/
         //</editor-fold>
         
        /*catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pengadaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pengadaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pengadaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pengadaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Guru("").setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cari;
    private javax.swing.JButton delet;
    private javax.swing.JTextField email;
    private javax.swing.JTextField idguru;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField kontak;
    private javax.swing.JTextField nama;
    private javax.swing.JRadioButton nv;
    private javax.swing.JComboBox<String> sekolah;
    private javax.swing.JTable tbl;
    private javax.swing.JRadioButton v;
    // End of variables declaration//GEN-END:variables

    private void simpan() {
        
       if(nama.getText().trim().equals("")){
                    
            JOptionPane.showMessageDialog(null,"Maaf, Nama Guru belum di isi!");
            nama.requestFocus();
        }
        else if(kontak.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, Kontak Guru belum di isi!");
            kontak.requestFocus();
        }
        else if(email.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, Email Guru belum di isi!");
            email.requestFocus();
        }
       else if(sekolah.getSelectedItem().equals("Pilih Sekolah")){
            JOptionPane.showMessageDialog(null,"Maaf,Lokasi Sekolah belum di isi!");
            sekolah.requestFocus();
        }
        else{
            try {
                Connection getConnection;
                getConnection = koneksi.getConnection();
                String sql = "insert into guru values(null,'"+nama.getText()+"','"+sek+"','"+kontak.getText()+"','"+email.getText()+"','"+valied+"','"+this.namapegawai+"')";
                PreparedStatement preparedStatement = getConnection.prepareStatement(sql);
                preparedStatement.execute();
                JOptionPane.showMessageDialog(null, "Data BERHASIL tersimpan" , "Informasi", JOptionPane.INFORMATION_MESSAGE);
               
            } catch(SQLException e) {
                JOptionPane.showMessageDialog(null, "Data GAGAL tersimpan" , "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }
            table();
            bersih();
            
             }
        }

    private void bersih() {
         
         nama.setText("");
         sekolah.setSelectedItem("Pilih Sekolah");
         kontak.setText("");
         email.setText("");    
    }

     @SuppressWarnings("empty-statement")
    private void table() {
 // DefaultTableModel model=new DefaultTableModel();
   /*model.addColumn("Tanggal");
         model.addColumn("Kode Barang");
         model.addColumn("Nama Barang");
         model.addColumn("Jenis Barang");
         model.addColumn("Jumah Barang");
         model.addColumn("harga");
         model.addColumn("Suplier");
         model.addColumn("Kondisi Barang");
         model.addColumn("Lokasi Barang");
         model.addColumn("keterangan");
         tbl.setModel(model);*/
         model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try{
        st=koneksi.getConnection().createStatement();
             String 
          sql = "select*from guru";
          res=st.executeQuery(sql);
          while(res.next()){
                model.addRow(new Object[]{
                res.getString("id_guru"),
                res.getString("nama_guru"),
                res.getString("nama_sekolah"),
                res.getString("kontak"),
                res.getString("email"),
                res.getString("Valid")
            });
         }
                
                
        }
        catch(SQLException e){
           JOptionPane.showMessageDialog(null, "Data GAGAL Di Ta" , "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
         tbl.setModel(model);
}

    private void jam() {
       ActionListener taskPerformer = (ActionEvent evt) -> {
    String nol_jam = "", nol_menit = "",nol_detik = "";
    java.util.Date dateTime = new java.util.Date();
    int nilai_jam = dateTime.getHours();
    int nilai_menit = dateTime.getMinutes();
    int nilai_detik = dateTime.getSeconds();
    if(nilai_jam <= 9) nol_jam= "0";
    if(nilai_menit <= 9) nol_menit= "0";
    if(nilai_detik <= 9) nol_detik= "0";
    String waktu = nol_jam + Integer.toString(nilai_jam);
    String menit = nol_menit + Integer.toString(nilai_menit);
    String detik = nol_detik + Integer.toString(nilai_detik);
    jLabel12.setText(waktu+":"+menit+":"+detik+"");
};
new Timer(1000, taskPerformer).start();
    }

    private void tgl() {
       java.util.Date skrg = new java.util.Date();
    java.text.SimpleDateFormat kal = new
    java.text.SimpleDateFormat("dd/MM/yyyy");
    jLabel11.setText(kal.format(skrg));
    }

    private void hapus() {
 int ok=JOptionPane.showConfirmDialog(null,"Apakah Yakin Mendelete Data ini ini???", "Confirmation",JOptionPane.YES_NO_CANCEL_OPTION);
       if (ok==0)
       {
        try {
            
                Connection getConnection;
                getConnection = koneksi.getConnection();
                String sql ="delete from guru where id_guru='"+idguru.getText()+"'"; 
                PreparedStatement preparedStatement = getConnection.prepareStatement(sql);
               JOptionPane.showMessageDialog(null, "Data BERHASIL  Terhapus" , "Informasi", JOptionPane.INFORMATION_MESSAGE);
               table();
            } catch(SQLException e) {
                JOptionPane.showMessageDialog(null, "Data GAGAL Di Hapus" , "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }
        //tbl.removeAll();
                  
                //bersih();
       
    }
    }

    private void edit() {
       String id= nama.getText();
                
                
                try
                    {
                Connection getConnection;
                getConnection = koneksi.getConnection();
                String sql="update guru set nama_guru='"+nama.getText()+"',nama_sekolah='"+sek+"',kontak='"+kontak.getText()+"',email='"+email.getText()+"',Valid='"+valied+"', Nama_Pegawai='"+this.namapegawai+"' where id_guru='"+idguru.getText()+"'";
                //String sql="update master set kdbr,nmbr=?,jnbr=?,jmlbr=?,konbr=?lokbr=?,suplier=?,hargabr=?,ket=? where kdbr='"+kodebr.getText()+"'";
                PreparedStatement preparedStatement = getConnection.prepareStatement(sql);
                        preparedStatement.executeUpdate();

                        JOptionPane.showMessageDialog(null,"Update Data Sukses");
                    }catch (SQLException e)
                    {
                        JOptionPane.showMessageDialog(null, "Update Data Gagal");
                    }
                table();
                bersih();
                }
           
        /*try {
                Connection getConnection;
                getConnection = koneksi.getConnection();
                String sql ="update from master set kdbr=?,nmbr=?,jnbr=?,jmlbr=?,konbr=?lokbr=?,suplier=?,hargabr=?,ket=? where kdbr='"+kodebr.getText()+"'"; 
                PreparedStatement preparedStatement = getConnection.prepareStatement(sql);
                preparedStatement.execute();
                
                JOptionPane.showMessageDialog(null, "Data BERHASIL  Terhapus" , "Informasi", JOptionPane.INFORMATION_MESSAGE);
               
            } catch(SQLException e) {
                JOptionPane.showMessageDialog(null, "Data GAGAL Di Hapus" , "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }*/

    private void cari() {
        String c = cari.getText();
        try
                    {
                        model.getDataVector().removeAllElements();
                        model.fireTableDataChanged();
                        Connection getConnection;
                getConnection = koneksi.getConnection();
                String sql = "Select * from guru where nama_guru like '%" + c + "%'";
                
                res=st.executeQuery(sql);
                
                    while (res.next()) {
                model.addRow(new Object[]{
                res.getString(1),
                res.getString(2),
                res.getString(3),
                res.getString(4),
                res.getString(4),
                res.getString(5),
                res.getString(6)
                
                    });
                
                
                tbl.setModel(model);
                    }
                  
                    }catch (SQLException e)
                    {
                        table();
                        JOptionPane.showMessageDialog(null, "Koneksi Gagal");
                    }
                //table();
                //bersih();
                

    }

    private void Nsekolah() {
        try{
            //PreparedStatement ps1 = null;
            Connection getConnection;
                getConnection = koneksi.getConnection();
                st = getConnection.createStatement();
                String sql1="select *from sekolah ";
                 //ps1=getConnection.prepareStatement(sql2);
                res=st.executeQuery(sql1);
                while (res.next()) {
                    
                    String des1 =res.getString("nama_sekolah");
                    sekolah.addItem(des1);
                    //JOptionPane.showMessageDialog(null, kec1);
                }
            }
        catch(SQLException e){
        
                JOptionPane.showMessageDialog(null, e);
        
            }

    }
    }


