/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugas_pv;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Inggo Landa (201643500634)
 */
public class instansi extends javax.swing.JFrame {

    public Connection con;
    public Statement st;
    public ResultSet res;
    public String konn;
    public DefaultTableModel model=new DefaultTableModel();
    private String tgl1;
    private String tgl2;
    public String koon,valied,will,namapegawai;
    /**
     * Creates new form pemeliharaan
     */
    public instansi(String namapegawai) {
        initComponents();
        this.namapegawai=namapegawai;
        ImageIcon ico = new ImageIcon("src/tugas_pv/img/iconpni.png");
        setIconImage(ico.getImage());
        model.addColumn("ID");
         model.addColumn("Nama");
         model.addColumn("Kontak");
         model.addColumn("Email");
         model.addColumn("Alamat");
         model.addColumn("Kategori");
         model.addColumn("Valid");
         tpemeliharaan.setModel(model);
         tb();
         tgl();
         jam();
         if (v.isSelected()){
        valied="Valied";
        }
        else 
        {
            valied="Tidak valied";
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Alamat = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        cari = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tpemeliharaan = new javax.swing.JTable();
        kontak = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        idinstansi = new javax.swing.JTextField();
        kategori = new javax.swing.JComboBox<>();
        v = new javax.swing.JRadioButton();
        nv = new javax.swing.JRadioButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PT Pelatos Nasional Indonesia");
        setLocation(new java.awt.Point(220, 54));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setText("Nama ");

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });

        jLabel7.setText("Kontak");

        jLabel8.setText("Alamat");

        Alamat.setColumns(20);
        Alamat.setRows(5);
        jScrollPane1.setViewportView(Alamat);

        jLabel9.setText("Email");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_pv/img/savee.png"))); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_pv/img/edite.png"))); // NOI18N
        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_pv/img/clear.png"))); // NOI18N
        jButton3.setText("Clear ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_pv/img/delet.png"))); // NOI18N
        jButton4.setText("Delet");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_pv/img/cari.png"))); // NOI18N
        jButton5.setText("Cari");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        tpemeliharaan.setAutoCreateRowSorter(true);
        tpemeliharaan.setForeground(new java.awt.Color(51, 51, 51));
        tpemeliharaan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode Instansi", "Nama", "Provinsi", "Kota", "Desa", "Kategori", "Kontak ", "Email", "Alamat"
            }
        ));
        tpemeliharaan.setGridColor(new java.awt.Color(255, 255, 255));
        tpemeliharaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tpemeliharaanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tpemeliharaan);

        kontak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kontakActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("REVOLUTION", 0, 24)); // NOI18N
        jLabel10.setText("INSTANSI");

        idinstansi.setText("    ");

        kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Kategori", "Dinas", "Swasta" }));
        kategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kategoriActionPerformed(evt);
            }
        });

        v.setText("Valid");

        nv.setText("Tidak Valid");

        jButton6.setText("Back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(62, 62, 62)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7)
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(184, 184, 184)
                                                .addComponent(jLabel9))
                                            .addComponent(kontak, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(idinstansi, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                            .addComponent(kategori, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(v)
                                            .addGap(31, 31, 31)
                                            .addComponent(nv))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(jButton1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton4)
                                        .addGap(94, 94, 94)
                                        .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton5))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 52, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(315, 315, 315)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton6)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jLabel3)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(idinstansi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(kontak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(69, 69, 69))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton4)
                            .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(v)
                            .addComponent(nv))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
   bersih();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        simpan();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tpemeliharaanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tpemeliharaanMouseClicked
   int i = tpemeliharaan.getSelectedRow();
//DefaultTableModel model=new DefaultTableModel();
if(i>-1){
   
   idinstansi.setText(model.getValueAt(i,0).toString());
   nama.setText(model.getValueAt(i,1).toString());
   kontak.setText(model.getValueAt(i,2).toString());
   email.setText(model.getValueAt(i,3).toString());
   Alamat.setText(model.getValueAt(i,4).toString());
   kategori.setSelectedItem(model.getValueAt(i,5).toString());
   valied =(model.getValueAt(i,6).toString());
   
}
if(valied.equals("Valied")){v.setSelected(true);nv.setSelected(false);}
           else{nv.setSelected(true);v.setSelected(false);
        }

    }//GEN-LAST:event_tpemeliharaanMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
edit();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
  hapus();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
cari();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void kategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kategoriActionPerformed
         will = (String) kategori.getSelectedItem();
    }//GEN-LAST:event_kategoriActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        try{
              model.getDataVector().removeAllElements();
              model.fireTableDataChanged();
              Connection getConnection;
                getConnection = koneksi.getConnection();
                String sql = "Select * from instansi where nama_instansi like '%" + nama.getText() + "%'";
                res=st.executeQuery(sql);
                
                    while (res.next()) {
                    //if(c.equals(res.getString("nama"))){
                model.addRow(new Object[]{
                res.getString("id_instansi"),
                res.getString("nama_instansi"),
                res.getString("alamat"),
                res.getString("kontak"),
                res.getString("email"),
                res.getString("kategori"),
                res.getString("Valid")
               

                
                    });
                    }
        }catch(SQLException e){
            
        }
        
    }//GEN-LAST:event_namaActionPerformed

    private void kontakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kontakActionPerformed
        tb();// TODO add your handling code here:
    }//GEN-LAST:event_kontakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(instansi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /*catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(pemeliharaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(pemeliharaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(pemeliharaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(pemeliharaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</ed
        //</editor-fold>
        /*catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(pemeliharaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(pemeliharaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(pemeliharaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(pemeliharaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</ed
        
        //</editor-fold>
       /*catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pemeliharaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pemeliharaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pemeliharaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pemeliharaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</ed

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new instansi("").setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Alamat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cari;
    private javax.swing.JTextField email;
    private javax.swing.JTextField idinstansi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> kategori;
    private javax.swing.JTextField kontak;
    private javax.swing.JTextField nama;
    private javax.swing.JRadioButton nv;
    private javax.swing.JTable tpemeliharaan;
    private javax.swing.JRadioButton v;
    // End of variables declaration//GEN-END:variables

    private void jam() {
       ActionListener taskPerformer = (ActionEvent evt) -> {
    String nol_jam = "", nol_menit = "",nol_detik = "";
    java.util.Date dateTime = new java.util.Date();
    int nilai_jam = dateTime.getHours();
    int nilai_menit = dateTime.getMinutes();
    int nilai_detik = dateTime.getSeconds();
    if(nilai_jam <= 9) nol_jam= "0";
    if(nilai_menit <= 9) nol_menit= "0";
    if(nilai_detik <= 9) nol_detik= "0";
    String waktu = nol_jam + Integer.toString(nilai_jam);
    String menit = nol_menit + Integer.toString(nilai_menit);
    String detik = nol_detik + Integer.toString(nilai_detik);
    jLabel1.setText(waktu+":"+menit+":"+detik+"");
};
new Timer(1000, taskPerformer).start();
    }

    private void tgl() {
       java.util.Date skrg = new java.util.Date();
    java.text.SimpleDateFormat kal = new
    java.text.SimpleDateFormat("dd/MM/yyyy");
    jLabel3.setText(kal.format(skrg));
    }

    
    
    private void tb() {
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try{
        st=koneksi.getConnection().createStatement();
             String 
       sql = "select*from instansi";
          res=st.executeQuery(sql);
          
          while(res.next()){
                model.addRow(new Object[]{
                res.getString("id_instansi"),
                res.getString("nama_instansi"),
                res.getString("kontak"),
                res.getString("email"),
                res.getString("alamat"),
                res.getString("kategori"),
                res.getString("Valid")
               
               
                
                        });
         }
                
                
        }
        catch(SQLException e){
           JOptionPane.showMessageDialog(null, "Data GAGAL Di Tampilankan" , "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }

    }

    private void bersih() {
        idinstansi.setText("");
        nama.setText("");
        kontak.setText("");
        email.setText("");
        Alamat.setText("");
 
    }

    private void simpan() {

 if(nama.getText().trim().equals("")){
                    
            JOptionPane.showMessageDialog(null,"Maaf, Nama Instansi belum di isi!");
            nama.requestFocus();
        }
        else if(kontak.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, Kontak Instansi belum di isi!");
            kontak.requestFocus();
        }
        else if(email.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, Email Instansi belum di isi!");
            email.requestFocus();
        }else if(Alamat.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, Alamat belum di isi!");
            Alamat.requestFocus();
        }
       else if(kategori.getSelectedItem().equals("Pilih Kategori")){
            JOptionPane.showMessageDialog(null,"Maaf,Kategori belum di isi!");
            kategori.requestFocus();
        }
        else{
       
            try {
                Connection getConnection;
                getConnection = koneksi.getConnection();
                String sql = "insert into instansi values(Null,'"+nama.getText()+"','"+Alamat.getText()+"','"+kontak.getText()+"','"+email.getText()+"','"+will+"','"+valied+"','"+this.namapegawai+"')";
                //String sql = "insert into master values(Null,'"+tgl1+"','"+kdbr3.getText()+"','"+nmbr3.getText()+"','"+jnbr3.getText()+"','"+jmlbr3.getText()+"','"+konn+"','"+nmpegawai.getText()+"','"+ket3.getText()+"','"+tgl2+"')";
                PreparedStatement preparedStatement = getConnection.prepareStatement(sql);
                preparedStatement.execute();
                //relasitambah();
                
                JOptionPane.showMessageDialog(null, "Data BERHASIL tersimpan" , "Informasi", JOptionPane.INFORMATION_MESSAGE);
               
            } catch(SQLException e) {
                JOptionPane.showMessageDialog(null, "Data GAGAL tersimpan" , "Informasi", JOptionPane.INFORMATION_MESSAGE);
            //}
            }
            tb();
            bersih();
       }
        
            }

    private void edit() {
try
                    {Connection getConnection;
                getConnection = koneksi.getConnection();
                //String sql="update pemeliharaan set tgl='"+tgl1+"',kdbr='"+kinstan.getText()+"',nmbr='"+nama.getText()+"',jnbr='"+jnbr3.getText()+"',jmlbr='"+jmlbr3.getText()+"',konbr='"+koon+"',nopegawai='"+nmpegawai.getText()+"',ket='"+Alamat.getText()+"',pengembalian='"+tgl2+"'where kdbr='"+kinstan.getText()+"'";
                String sql = "update instansi set nama_instansi='"+nama.getText()+"',Alamat='"+Alamat.getText()+"',kontak='"+kontak.getText()+"',email='"+email.getText()+"',kategori='"+will+"',valid='"+valied+"',Nama_Pegawai='"+this.namapegawai+"' where id_instansi='"+idinstansi.getText()+"'";
                PreparedStatement preparedStatement = getConnection.prepareStatement(sql);
                       
                        preparedStatement.executeUpdate();                //String sql="update master set tgl='"+tgl+"',kdbr='"+kodebr.getText()+"',nmbr='"+namabr.getText()+"',jnbr='"+jenisbr.getText()+"',jmlbr='"+jumlahbr.getText()+"',konbr='"+kondisi.getText()+"',lokbr='"+lokbr.getText()+"',suplier='"+suplier.getText()+"',hargabr='"+harga.getText()+"',ket='"+ket.getText()+"'where kdbr='"+kodebr.getText()+"'";


                        JOptionPane.showMessageDialog(null,"Update Data Sukses");
                    }catch (SQLException e)
                    {
                        JOptionPane.showMessageDialog(null, "Update Data Gagal");
                    }
                tb();
                bersih();
                
    }

    private void hapus() {
int ok=JOptionPane.showConfirmDialog(null,"Apakah Yakin Mendelete Data ini ini???", "Confirmation",JOptionPane.YES_NO_CANCEL_OPTION);
       if (ok==0)
       {
        try {
            
                Connection getConnection;
                getConnection = koneksi.getConnection();
                String sql ="delete from instansi where id_instansi='"+idinstansi.getText()+"'"; 
                PreparedStatement preparedStatement = getConnection.prepareStatement(sql);
                preparedStatement.execute();
                //relasinambah();
                JOptionPane.showMessageDialog(null, "Data BERHASIL  Terhapus" , "Informasi", JOptionPane.INFORMATION_MESSAGE);
               
            } catch(SQLException e) {
                JOptionPane.showMessageDialog(null, "Data GAGAL Di Hapus" , "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }
        //tbl.removeAll();
          tb();        
                bersih();
       
    }
    }

    /*private void relasitambah() throws SQLException {
    
          }    }
*/
    private void cari() {
try
                    {
                        model.getDataVector().removeAllElements();
                        model.fireTableDataChanged();
                        Connection getConnection;
                getConnection = koneksi.getConnection();
                String sql = "Select * from instansi where nama_instansi like '%" + cari.getText() + "%'";
                res=st.executeQuery(sql);
                while (res.next()) {
                model.addRow(new Object[]{
                res.getString("id_instansi"),
                res.getString("nama_instansi"),
                res.getString("kontak"),
                res.getString("email"),
                res.getString("alamat"),
                res.getString("Valid")
                
});
                
                tpemeliharaan.setModel(model);
}                        

                        
                    }catch (SQLException e)
                    {
                        tb();
                        JOptionPane.showMessageDialog(null, "Data Tidak Ditemukan");
                    }
                //table();
                bersih();
                

       
    
    }

    private void temukan() {
 try
                    {
                       
                        Connection getConnection;
                getConnection = koneksi.getConnection();
                String sql = "Select * from instansi WHERE nama_instansi like '%" + nama.getText() + "%'";
                
                res=st.executeQuery(sql);
                while (res.next()) {
               
         idinstansi.setText(res.getString("id_instansi"));
         nama.setText(res.getString("nama_instansi"));
         kontak.setText(res.getString("jnbr"));
         email.setText(res.getString("jmlbr"));
         kategori.setSelectedItem(res.getString("kategori"));
         
         Alamat.setText(res.getString("alamat"));       
   
                
}                        

                        
                    }catch (SQLException e)
                    {
                        JOptionPane.showMessageDialog(null, "Data Tidak Ditemukan");
                    }
                //table();
                //bersih();
                

    }
    }
    

