/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugas_pv;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
/**
 *
 * @author Inggo Landa (201643500364)
 */
public class siswa extends javax.swing.JFrame {

    public Connection con;
    public Statement st;
    public ResultSet res,res1;
    public DefaultTableModel model=new DefaultTableModel();
    public String jn,status,valied;
    public String kel;
    public String id,idsek;
    public String bidang1,sekolah1,program1,prestasi1,namapegawai;
    //public String deepp;
    
    public siswa(String namapegawai) {
        initComponents();
        this.namapegawai=namapegawai;
        
        ImageIcon ico = new ImageIcon("src/tugas_pv/img/iconpni.png");
        setIconImage(ico.getImage());
        model.addColumn("ID");
         model.addColumn("Nama");
         model.addColumn("Jenis Kelamin");
         model.addColumn("Kelas");
         model.addColumn("Bidang");
         model.addColumn("Sekolah");
         model.addColumn("Kontak ");
         model.addColumn("Email");
         model.addColumn("Program");
         model.addColumn("Prestasi");
         model.addColumn("Status");
         model.addColumn("Valid");
         
         tsiswa.setModel(model);
         table();
                        tgl();
                        jam();
                        Nsekolah();
                        AutoCompleteDecorator.decorate(sekolah);
                        
    
   
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextField2 = new javax.swing.JTextField();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        cari = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nama_siswa = new javax.swing.JTextField();
        lk = new javax.swing.JRadioButton();
        pr = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tsiswa = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        bidang = new javax.swing.JComboBox<>();
        sekolah = new javax.swing.JComboBox<>();
        kontak = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        program = new javax.swing.JComboBox<>();
        prestasi = new javax.swing.JComboBox<>();
        y = new javax.swing.JRadioButton();
        n = new javax.swing.JRadioButton();
        v = new javax.swing.JRadioButton();
        nv = new javax.swing.JRadioButton();
        NIS = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        kelas = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();

        jTextField2.setText("jTextField2");

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PT Pelatos Nasional Indonesia - Marketing");

        jPanel1.setBackground(new java.awt.Color(176, 196, 222));
        jPanel1.setPreferredSize(new java.awt.Dimension(723, 723));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Data Siswa");

        jLabel3.setText("Nama Siswa");

        jLabel4.setText("Kelas");

        jLabel5.setText("Bidang");

        jLabel6.setText("Sekolah");

        jLabel7.setText("Kontak");

        jLabel8.setText("Jenis Kelamin");

        nama_siswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_siswaActionPerformed(evt);
            }
        });

        buttonGroup1.add(lk);
        lk.setText("Laki - Laki");
        lk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lkActionPerformed(evt);
            }
        });

        buttonGroup1.add(pr);
        pr.setText("Perempuan");
        pr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_pv/img/savee.png"))); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_pv/img/edite.png"))); // NOI18N
        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_pv/img/clear.png"))); // NOI18N
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_pv/img/delet.png"))); // NOI18N
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_pv/img/cari.png"))); // NOI18N
        jButton5.setText("Cari");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        tsiswa.setBackground(new java.awt.Color(220, 220, 220));
        tsiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Siswa", "Nama", "Jenis Kelamin", "Kelas", "Bidang", "Sekolah", "Kontak", "Email", "Program", "Prestasil", "Status"
            }
        ));
        tsiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tsiswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tsiswa);

        jLabel9.setText("Email");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText(" ");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("     ");

        jLabel13.setText("Program");

        jLabel15.setText("Prestasi");

        bidang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Bidang Studi", "Matematika", "Fisika", "Kimia ", "Biologi", "Ekonomi", "Geografi", "Kebumian ", "Astronomi ", "Komputer" }));
        bidang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bidangActionPerformed(evt);
            }
        });

        sekolah.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih sekolah" }));
        sekolah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sekolahActionPerformed(evt);
            }
        });

        program.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Program", "Privat", "Group", "Rutin", "Intensif", "Akbar" }));
        program.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                programActionPerformed(evt);
            }
        });

        prestasi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Prestasi", "Emas", "Perak", "Perunggu", "No Medali" }));
        prestasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prestasiActionPerformed(evt);
            }
        });

        y.setText("Aktif");
        y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yActionPerformed(evt);
            }
        });

        n.setText("Non Aktif");
        n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nActionPerformed(evt);
            }
        });

        v.setText("Valied");
        v.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vActionPerformed(evt);
            }
        });

        nv.setText("Non Valied");
        nv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nvActionPerformed(evt);
            }
        });

        NIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NISActionPerformed(evt);
            }
        });

        jLabel2.setText("NIS");

        jButton6.setText("Back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        kelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Kelas", "7", "8", "9", "10", "11", "12" }));
        kelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelasActionPerformed(evt);
            }
        });

        jLabel10.setText("jLabel10");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(v)
                        .addGap(35, 35, 35)
                        .addComponent(nv)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(268, 268, 268)
                        .addComponent(jButton6))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel10)
                .addGap(46, 46, 46)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 301, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel2)
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NIS, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel5))
                                    .addGap(29, 29, 29)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(nama_siswa, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(lk)
                                            .addGap(18, 18, 18)
                                            .addComponent(pr))
                                        .addComponent(bidang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(sekolah, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(kontak)
                                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton4)))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(cari)
                                    .addGap(14, 14, 14)
                                    .addComponent(jButton5))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel13)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(program, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel15)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(y)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(n))
                                                .addComponent(prestasi, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(0, 0, Short.MAX_VALUE)))))
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(79, 79, 79)
                .addComponent(kelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(v)
                    .addComponent(nv))
                .addContainerGap(416, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(108, 108, 108)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nama_siswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel13)
                        .addComponent(program, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lk)
                        .addComponent(pr)
                        .addComponent(jLabel8))
                    .addGap(19, 19, 19)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel15)
                        .addComponent(prestasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(bidang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(1, 1, 1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(y)
                        .addComponent(n))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(sekolah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(23, 23, 23)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(kontak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton4)
                        .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton5)
                        .addComponent(jButton3)
                        .addComponent(jButton2)
                        .addComponent(jButton1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        simpan();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        bersih();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        hapus();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            edit();
        } catch (SQLException ex) {
            Logger.getLogger(siswa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void prActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prActionPerformed
        jn="Perempuan";
    }//GEN-LAST:event_prActionPerformed

    private void lkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lkActionPerformed
        jn="Laki-Laki";
        table();
    }//GEN-LAST:event_lkActionPerformed

    private void tsiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tsiswaMouseClicked
      int i = tsiswa.getSelectedRow();
if(i>-1){
   NIS.setText(model.getValueAt(i, 0).toString()); 
   nama_siswa.setText(model.getValueAt(i, 1).toString());
   jn =(model.getValueAt(i,2).toString());
   kelas.setSelectedItem(model.getValueAt(i,3).toString());
   bidang.setSelectedItem(model.getValueAt(i,4).toString());
   sekolah.setSelectedItem(model.getValueAt(i,5).toString());
   kontak.setText(model.getValueAt(i,6).toString());
   email.setText(model.getValueAt(i,7).toString());
   program.setSelectedItem(model.getValueAt(i,8).toString());
   prestasi.setSelectedItem(model.getValueAt(i,9).toString());
   status =(model.getValueAt(i,10).toString());
   valied =(model.getValueAt(i,11).toString());
   
}
if(jn.equals("Laki-Laki"))
{lk.setSelected(true);pr.setSelected(false);}
else{lk.setSelected(false);pr.setSelected(true);
}
if(status.equals("Aktif")){y.setSelected(true);n.setSelected(false);}
else{n.setSelected(true);y.setSelected(false);
}
if(valied.equals("Valied")){v.setSelected(true);nv.setSelected(false);}
           else{nv.setSelected(true);v.setSelected(false);
        }


       
    }//GEN-LAST:event_tsiswaMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            cari();
        } catch (SQLException ex) {
            Logger.getLogger(siswa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void bidangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bidangActionPerformed
bidang1 = (String) bidang.getSelectedItem();
    }//GEN-LAST:event_bidangActionPerformed

    private void sekolahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sekolahActionPerformed
 sekolah1 = (String) sekolah.getSelectedItem();
    }//GEN-LAST:event_sekolahActionPerformed

    private void programActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_programActionPerformed
program1 = (String) program.getSelectedItem();
    }//GEN-LAST:event_programActionPerformed

    private void prestasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prestasiActionPerformed
prestasi1 = (String) prestasi.getSelectedItem();
    }//GEN-LAST:event_prestasiActionPerformed

    private void nvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nvActionPerformed
        valied="Tidak Valied";
    }//GEN-LAST:event_nvActionPerformed

    private void vActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vActionPerformed
        valied="Valied";
    }//GEN-LAST:event_vActionPerformed

    private void NISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NISActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NISActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void nama_siswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_siswaActionPerformed
        try{
                model.getDataVector().removeAllElements();
                model.fireTableDataChanged();
                Connection getConnection;
                getConnection = koneksi.getConnection();
                String sql = "Select * from siswa where nama like '%" + nama_siswa.getText() + "%'";
                res1=st.executeQuery(sql);
                while (res1.next()) {
                    
                    model.addRow(new Object[]{
                res1.getString("NIS"),
                res1.getString("nama"),
                res1.getString("jk"),
                res1.getString("kelas"),
                res1.getString("bidang"),
                res1.getString("nama_sekolah"),
                res1.getString("kontak"),
                res1.getString("email"),
                res1.getString("program"),
                res1.getString("prestasi"),
                res1.getString("status"),
                res1.getString("valid")
                        
                    
                    }
                    );
                }
        }catch (SQLException ex){
            table();
        }
        
        
    }//GEN-LAST:event_nama_siswaActionPerformed

    private void yActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yActionPerformed
       
        status="Aktif";
    }//GEN-LAST:event_yActionPerformed

    private void nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nActionPerformed
        status="tidak aktif";
    }//GEN-LAST:event_nActionPerformed

    private void kelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelasActionPerformed
        kel = (String) kelas.getSelectedItem();
        
        
    }//GEN-LAST:event_kelasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new siswa("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NIS;
    private javax.swing.JComboBox<String> bidang;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JTextField cari;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JComboBox<String> kelas;
    private javax.swing.JTextField kontak;
    private javax.swing.JRadioButton lk;
    private javax.swing.JRadioButton n;
    private javax.swing.JTextField nama_siswa;
    private javax.swing.JRadioButton nv;
    private javax.swing.JRadioButton pr;
    private javax.swing.JComboBox<String> prestasi;
    private javax.swing.JComboBox<String> program;
    private javax.swing.JComboBox<String> sekolah;
    private javax.swing.JTable tsiswa;
    private javax.swing.JRadioButton v;
    private javax.swing.JRadioButton y;
    // End of variables declaration//GEN-END:variables

    private void table() {
   model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try{
        st=koneksi.getConnection().createStatement();
             String sql = "select*from siswa";
          res=st.executeQuery(sql);
          
          while(res.next()){
                model.addRow(new Object[]{
                res.getString("NIS"),
                res.getString("nama"),
                res.getString("jk"),
                res.getString("kelas"),
                res.getString("bidang"),
                res.getString("nama_sekolah"),
                res.getString("kontak"),
                res.getString("email"),
                res.getString("program"),
                res.getString("prestasi"),
                res.getString("status"),
                res.getString("valid")
                        
                        });
         }
                
                
        }
        catch(SQLException e){
           JOptionPane.showMessageDialog(null, "Data GAGAL Di Ta" , "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
         tsiswa.setModel(model);
    }

    private void tgl() {
       java.util.Date skrg = new java.util.Date();
    java.text.SimpleDateFormat kal = new
    java.text.SimpleDateFormat("dd/MM/yyyy");
    jLabel11.setText(kal.format(skrg));

    }

    private void jam() {
ActionListener taskPerformer = (ActionEvent evt) -> {
    String nol_jam = "", nol_menit = "",nol_detik = "";
    java.util.Date dateTime = new java.util.Date();
    int nilai_jam = dateTime.getHours();
    int nilai_menit = dateTime.getMinutes();
    int nilai_detik = dateTime.getSeconds();
    if(nilai_jam <= 9) nol_jam= "0";
    if(nilai_menit <= 9) nol_menit= "0";
    if(nilai_detik <= 9) nol_detik= "0";
    String waktu = nol_jam + Integer.toString(nilai_jam);
    String menit = nol_menit + Integer.toString(nilai_menit);
    String detik = nol_detik + Integer.toString(nilai_detik);
    jLabel12.setText(waktu+":"+menit+":"+detik+"");
    

};
new Timer(1000, taskPerformer).start();
}

    private void simpan() {
        if(NIS.getText().trim().equals("")){  
            JOptionPane.showMessageDialog(null,"Maaf, NIS belum di isi!");
            NIS.requestFocus();
        }else if(nama_siswa.getText().trim().equals("")){    
            JOptionPane.showMessageDialog(null,"Maaf, Nama Siswa belum di isi!");
            nama_siswa.requestFocus();
        }else if(bidang.getSelectedItem().equals("Pilih Bidang Studi")){
            JOptionPane.showMessageDialog(null,"Maaf,Bidang belum di Pilih!");
            bidang.requestFocus();
        }else if(kelas.getSelectedItem().equals("Pilih Kelas")){
            JOptionPane.showMessageDialog(null,"Maaf, Kelas belum di Pilih!");
            kelas.requestFocus();
        }else if(sekolah.getSelectedItem().equals("Pilih sekolah")){
            JOptionPane.showMessageDialog(null,"Maaf,Lokasi Sekolah belum di Pilih!");
            sekolah.requestFocus();
        }
        else if(kontak.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, Kontak Guru belum di isi!");
            kontak.requestFocus();
        }
        else if(email.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, Email Guru belum di isi!");
            email.requestFocus();
        }
       else if(program.getSelectedItem().equals("Pilih Program")){
            JOptionPane.showMessageDialog(null,"Maaf,Program belum di Pilih!");
            sekolah.requestFocus();
        }else if(prestasi.getSelectedItem().equals("Pilih Prestasi")){
            JOptionPane.showMessageDialog(null,"Maaf,Prestasi belum di Pilih!");
            sekolah.requestFocus();
        }
        
        else{
        try{
     
                Connection getConnection;
                getConnection = koneksi.getConnection();
                String sql = "insert into siswa values('"+NIS.getText()+"','"+nama_siswa.getText()+"','"+jn+"','"+kel+"','"+bidang1+"','"+sekolah1+"','"+kontak.getText()+"','"+email.getText()+"','"+program1+"','"+prestasi1+"','"+status+"','"+valied+"','"+this.namapegawai+"')";
                PreparedStatement preparedStatement = getConnection.prepareStatement(sql);
                preparedStatement.execute();
                JOptionPane.showMessageDialog(null, "Data BERHASIL tersimpan" , "Informasi", JOptionPane.INFORMATION_MESSAGE);
               
            } catch(SQLException e) {
                JOptionPane.showMessageDialog(null, "Data GAGAL tersimpan" , "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }
           table();
            bersih();
       }
        }

    private void bersih() {
      nama_siswa.setText("");
      lk.setSelected(true);      
      
    }

    private void hapus() {
int ok=JOptionPane.showConfirmDialog(null,"Apakah Yakin Mendelete Data ini ini???", "Confirmation",JOptionPane.YES_NO_CANCEL_OPTION);
       
if (ok==0)
       {
        try {
            
                Connection getConnection;
                getConnection = koneksi.getConnection();
                String sql ="delete from siswa where NIS='"+NIS.getText()+"'"; 
                PreparedStatement preparedStatement = getConnection.prepareStatement(sql);
                preparedStatement.execute();
                JOptionPane.showMessageDialog(null, "Data BERHASIL  Terhapus" , "Informasi", JOptionPane.INFORMATION_MESSAGE);
               
            } catch(SQLException e) {
                JOptionPane.showMessageDialog(null, "Data GAGAL Di Hapus" , "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }
        //tbl.removeAll();
          table();        
                bersih();
       
    }
    }

    private void edit() throws SQLException 
    {
        
        try{
                
            Connection getConnection;
                getConnection = koneksi.getConnection();
         
                String sql="update siswa set nama='"+nama_siswa.getText()+"',jk='"+jn+"',kelas='"+kel+"',bidang='"+bidang1+"',nama_sekolah='"+sekolah1+"',kontak='"+kontak.getText()+"',email='"+email.getText()+"',program='"+program1+"',prestasi='"+prestasi1+"',status='"+status+"',valid='"+valied+"',Nama_Pegawai='"+this.namapegawai+"' where NIS='"+NIS.getText()+"'";
                //String sql="update siswa set kdbr,nmbr=?,jnbr=?,jmlbr=?,konbr=?lokbr=?,suplier=?,hargabr=?,ket=? where kdbr='"+kodebr.getText()+"'";
                PreparedStatement preparedStatement = getConnection.prepareStatement(sql);
                           preparedStatement.executeUpdate();
                             //relasikurang();
                        JOptionPane.showMessageDialog(null,"Update Data Sukses");
                    }catch (SQLException e)
                    {
                        JOptionPane.showMessageDialog(null, "Update Data Gagal");
                    }
                table();
                bersih();
    }

    private void cari() throws SQLException {
       try
                    {
                        model.getDataVector().removeAllElements();
                        model.fireTableDataChanged();
                        Connection getConnection;
                getConnection = koneksi.getConnection();
                String sql = "Select * from siswa where nama like'%" + cari.getText() + "%'";
                
                res=st.executeQuery(sql);
                while (res.next()) {
                model.addRow(new Object[]{
                res.getString(1),
                res.getString(2),
                res.getString(3),
                res.getString(4),
                res.getString(4),
                res.getString(5),
                res.getString(6),
                res.getString(7),
                res.getString(8),
                res.getString(9),
                
                
});
                
                tsiswa.setModel(model);
    } }catch (SQLException e)
                    {
                      table();
                        JOptionPane.showMessageDialog(null, "Data Tidak Ditemukan");
                    }
                //table();
                bersih();
    }

    private void fildcombo() {
        try{Connection getConnection;
                getConnection = koneksi.getConnection();
                String sql="select * from sekolah";
                res=st.executeQuery(sql);
                while (res.next()) {
                    String s =res.getString("lokasi_propinsi");
                    sekolah.addItem(s);
                }
               }
            
            
        
        catch(SQLException e){
        
        JOptionPane.showMessageDialog(null, e);
        
        }
        
        
    }

    private void Nsekolah() {
           try{
            //PreparedStatement ps1 = null;
            Connection getConnection;
                getConnection = koneksi.getConnection();
                st = getConnection.createStatement();
                String sql1="select *from sekolah ";
                 //ps1=getConnection.prepareStatement(sql2);
                res=st.executeQuery(sql1);
                while (res.next()) {
                    
                    String des1 =res.getString("nama_sekolah");
                    sekolah.addItem(des1);
                    //JOptionPane.showMessageDialog(null, kec1);
                }
            }
        catch(SQLException e){
        
                JOptionPane.showMessageDialog(null, e);
        
            }

    }
}
    


