/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugas_pv;

import static java.awt.SystemColor.menu;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener; 
import java.io.File;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;

import net.sf.jasperreports.engine.JasperFillManager;

import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

public class Utama extends javax.swing.JFrame {
    
    public Connection con;
    public Statement st;
    public ResultSet res;
    JasperReport JasRep,JasRep1;
    JasperPrint JasPri;
    Map param= new HashMap();
    JasperDesign JasDes,JasDes1;
    String namapegawai;
    
public void setTanggal(){
    java.util.Date skrg = new java.util.Date();
    java.text.SimpleDateFormat kal = new
    java.text.SimpleDateFormat("dd/MM/yyyy");
    jLabel4.setText(kal.format(skrg));
    }


   
    public Utama() {

        initComponents();
        Locale locale = new Locale("id","ID");
        Locale.setDefault(locale);
        ImageIcon ico = new ImageIcon("src/tugas_pv/img/iconpni.png");
        setIconImage(ico.getImage());
         setTanggal();         
        marketing.setEnabled(false);
        report.setEnabled(false);
        login.setVisible(false);
        data.setEnabled(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        login = new javax.swing.JInternalFrame();
        user = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        data = new javax.swing.JMenu();
        User = new javax.swing.JMenuItem();
        siswa = new javax.swing.JMenuItem();
        sekolah = new javax.swing.JMenuItem();
        Guru = new javax.swing.JMenuItem();
        mitra = new javax.swing.JMenuItem();
        instansi = new javax.swing.JMenuItem();
        marketing = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        report = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PT Pelatos Nasional Indonesia");

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(1920, 1080));

        login.setBackground(new java.awt.Color(153, 153, 153));
        login.setTitle("Login");
        login.setVisible(true);
        login.getContentPane().setLayout(null);

        user.setBorder(null);
        user.setOpaque(false);
        login.getContentPane().add(user);
        user.setBounds(180, 190, 190, 30);

        pass.setToolTipText("");
        pass.setBorder(null);
        pass.setOpaque(false);
        login.getContentPane().add(pass);
        pass.setBounds(180, 250, 200, 20);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("REVOLUTION", 0, 18)); // NOI18N
        jButton1.setText("login");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        login.getContentPane().add(jButton1);
        jButton1.setBounds(140, 323, 250, 30);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        login.getContentPane().add(jPanel1);
        jPanel1.setBounds(180, 190, 200, 30);

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        login.getContentPane().add(jPanel5);
        jPanel5.setBounds(140, 280, 250, 20);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        login.getContentPane().add(jPanel3);
        jPanel3.setBounds(100, 320, 330, 40);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        login.getContentPane().add(jPanel2);
        jPanel2.setBounds(180, 240, 130, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_pv/img/Untitled-1.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        login.getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 530, 460);

        jLabel7.setFont(new java.awt.Font("Della Respira", 0, 24)); // NOI18N
        jLabel7.setText("          ");

        jLabel1.setFont(new java.awt.Font("Della Respira", 0, 24)); // NOI18N
        jLabel1.setText("          ");

        jLabel2.setFont(new java.awt.Font("Della Respira", 0, 24)); // NOI18N
        jLabel2.setText("           ");

        jLabel3.setFont(new java.awt.Font("Della Respira", 0, 36)); // NOI18N
        jLabel3.setText("            ");

        jLabel4.setFont(new java.awt.Font("Della Respira", 0, 36)); // NOI18N
        jLabel4.setText("           ");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_pv/img/BGpni.png"))); // NOI18N
        jLabel6.setPreferredSize(new java.awt.Dimension(678, 640));

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel1)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(120, 120, 120)
                        .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1459, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(96, 96, 96))
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(78, 78, 78))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(53, 53, 53))))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel4)
                        .addGap(78, 78, 78)
                        .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(470, Short.MAX_VALUE))
        );

        file.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_pv/img/file_1.png"))); // NOI18N
        file.setText("File");
        file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileActionPerformed(evt);
            }
        });

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_pv/img/open.png"))); // NOI18N
        jMenuItem1.setText("Open");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        file.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_pv/img/clouse.png"))); // NOI18N
        jMenuItem2.setText("Close");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        file.add(jMenuItem2);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_pv/img/logout.png"))); // NOI18N
        jMenuItem3.setText("Logout");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        file.add(jMenuItem3);

        jMenuBar1.add(file);

        data.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_pv/img/data_1.png"))); // NOI18N
        data.setText("Data");
        data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataActionPerformed(evt);
            }
        });

        User.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_pv/img/i.png"))); // NOI18N
        User.setText("User");
        User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserActionPerformed(evt);
            }
        });
        data.add(User);

        siswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_pv/img/siswa.png"))); // NOI18N
        siswa.setText("Siswa");
        siswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siswaActionPerformed(evt);
            }
        });
        data.add(siswa);

        sekolah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_pv/img/school_1.png"))); // NOI18N
        sekolah.setText("Sekolah");
        sekolah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sekolahActionPerformed(evt);
            }
        });
        data.add(sekolah);

        Guru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_pv/img/teacher_1.png"))); // NOI18N
        Guru.setText("Guru");
        Guru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuruActionPerformed(evt);
            }
        });
        data.add(Guru);

        mitra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_pv/img/mitra_1.png"))); // NOI18N
        mitra.setText("Mitra");
        mitra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitraActionPerformed(evt);
            }
        });
        data.add(mitra);

        instansi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_pv/img/instansi_1.png"))); // NOI18N
        instansi.setText("Instansi");
        instansi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instansiActionPerformed(evt);
            }
        });
        data.add(instansi);

        jMenuBar1.add(data);

        marketing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_pv/img/marketing_1.png"))); // NOI18N
        marketing.setText("Marketing");
        marketing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marketingActionPerformed(evt);
            }
        });

        jMenuItem9.setText("Filter Data");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        marketing.add(jMenuItem9);

        jMenuBar1.add(marketing);

        report.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_pv/img/report_1.png"))); // NOI18N
        report.setText("Report");

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_pv/img/i.png"))); // NOI18N
        jMenuItem11.setText("Laporan User");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        report.add(jMenuItem11);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_pv/img/school.png"))); // NOI18N
        jMenuItem5.setText("Laporan Sekolah");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        report.add(jMenuItem5);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_pv/img/teacher.png"))); // NOI18N
        jMenuItem6.setText("Laporan Guru");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        report.add(jMenuItem6);

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_pv/img/siswa.png"))); // NOI18N
        jMenuItem7.setText("Laporan Siswa");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        report.add(jMenuItem7);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_pv/img/instansi.png"))); // NOI18N
        jMenuItem8.setText("Laporan Instansi");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        report.add(jMenuItem8);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas_pv/img/mitra.png"))); // NOI18N
        jMenuItem4.setText("Laporan Mitra");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        report.add(jMenuItem4);

        jMenuBar1.add(report);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 2580, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 1075, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 186, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
         login.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
      dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataActionPerformed
        
    }//GEN-LAST:event_dataActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        
        int ok=JOptionPane.showConfirmDialog(null,"Apakah Anda ingin Keluar???", "Confirmation",JOptionPane.YES_NO_CANCEL_OPTION);
       if (ok==0){
        data.setEnabled(false);
        marketing.setEnabled(false);
        report.setEnabled(false);
        login.setVisible(true);
       }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void siswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siswaActionPerformed
        siswa sis = new siswa(namapegawai);
       sis.setVisible(true);
    }//GEN-LAST:event_siswaActionPerformed

    private void sekolahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sekolahActionPerformed
        sekolah sek = new sekolah(namapegawai);
       sek.setVisible(true);
    }//GEN-LAST:event_sekolahActionPerformed

    private void GuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuruActionPerformed
       Guru gr = new Guru(namapegawai);
       gr.setVisible(true);
    }//GEN-LAST:event_GuruActionPerformed

    private void mitraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitraActionPerformed
        mitra m = new mitra(namapegawai);
       m.setVisible(true);
    }//GEN-LAST:event_mitraActionPerformed

    private void instansiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instansiActionPerformed
        instansi i = new instansi(namapegawai);
       i.setVisible(true);
    }//GEN-LAST:event_instansiActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed

        con = koneksi.getConnection();
        try {
           InputStream file1 = getClass().getResourceAsStream("/Ireport/mitra.jrxml");
            JasDes = JRXmlLoader.load(file1);
            param.clear();
            JasRep =JasperCompileManager.compileReport(JasDes);
            JasPri = JasperFillManager.fillReport(JasRep, param,con);
            JasperViewer.viewReport(JasPri,false);
        } catch (JRException e) {
           JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        con = koneksi.getConnection();
        try {
            
            //File fl = new File("src/Ireport/guru.jrxml");
            InputStream file1 = getClass().getResourceAsStream("/Ireport/guru.jrxml");
            JasDes = JRXmlLoader.load(file1);
            param.clear();
            JasRep =JasperCompileManager.compileReport(JasDes);
            JasPri = JasperFillManager.fillReport(JasRep, param,con);
            JasperViewer.viewReport(JasPri,false);
        } catch (JRException e) {
            //Logger.getLogger(Utama.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        con = koneksi.getConnection();
        try {
            //File file = new File("src/Ireport/Rpengadaan.jrxml");
            //File f2 = new File("src/Ireport/Sekolah1.jrxml");
            InputStream file1 = getClass().getResourceAsStream("/Ireport/Sekolah.jrxml");
            JasDes = JRXmlLoader.load(file1);
            param.clear();
            JasRep =JasperCompileManager.compileReport(JasDes);
            JasPri = JasperFillManager.fillReport(JasRep, param,con);
            JasperViewer.viewReport(JasPri,false);
        } catch (JRException e) {
            //JOptionPane.showMessageDialog(null, "Maaf password atau username anda salah");
            //Logger.getLogger(Utama.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void marketingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marketingActionPerformed
      
      
    }//GEN-LAST:event_marketingActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed

        
        con=koneksi.getConnection();
        try{

            InputStream file1 = getClass().getResourceAsStream("/Ireport/instansi.jrxml");
            JasDes = JRXmlLoader.load(file1);
            param.clear();
            JasRep = JasperCompileManager.compileReport(JasDes);
            JasPri = JasperFillManager.fillReport(JasRep, param, con);
            JasperViewer.viewReport(JasPri,false);
        }catch(JRException e){
            //JOptionPane.showMessageDialog(null,ex); 
            JOptionPane.showMessageDialog(null, e);
        }
        
        
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
       marketing mr = new marketing();
      mr.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        con = koneksi.getConnection();
        try {

            InputStream file1 = getClass().getResourceAsStream("/Ireport/siswa.jrxml");
            JasDes = JRXmlLoader.load(file1);
            param.clear();
            JasRep =JasperCompileManager.compileReport(JasDes);
            JasPri = JasperFillManager.fillReport(JasRep, param,con);
            JasperViewer.viewReport(JasPri,false);
        } catch (JRException e) {
 
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed

    }//GEN-LAST:event_jButton1KeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String us = user.getText();
        String ps = pass.getText();
        try {
            con = koneksi.getConnection();
            st = con.createStatement();
           // con = koneksi.getConnection();
            String sql = "select * from user where Username = '"+us+"' and Password = '"+ps+"'";
            res = st.executeQuery(sql);
            if(res.next()){
                namapegawai=res.getString("Nama_Pegawai");
                if(res.getString("Jabatan").equals("Kepala Marketing")){
                    login.setVisible(false);
                    data.setEnabled(true);
                        User.setEnabled(true);
                        siswa.setEnabled(false);
                        sekolah.setEnabled(false);
                        Guru.setEnabled(false);
                        mitra.setEnabled(false);
                        instansi.setEnabled(false);
                    marketing.setEnabled(false);
                    report.setEnabled(true);
              
     
                    
                    JOptionPane.showMessageDialog(null,"Selamat Datang Bapak/Ibu : "+res.getString("Nama_Pegawai"));
                }else if(res.getString("Jabatan").equals("Staff Marketing")){
                    login.setVisible(false);
                    data.setEnabled(true);
                    User.setEnabled(false);
                    report.setEnabled(false);
                    marketing.setEnabled(true);
                 siswa.setEnabled(true);
                    sekolah.setEnabled(true);
                    Guru.setEnabled(true);
                    mitra.setEnabled(true);
                    instansi.setEnabled(true);
                      JOptionPane.showMessageDialog(null,"Selamat Datang Bapak/Ibu : "+res.getString("Nama_Pegawai"));
                }
            else{
                JOptionPane.showMessageDialog(null, "Maaf password atau username anda salah");
                user.setText("");
                pass.setText("");
                user.requestFocus();
            }
        }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Maaf Data Tidak Di Temukan");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserActionPerformed
        User us = new User();
       us.setVisible(true);
    }//GEN-LAST:event_UserActionPerformed

    private void fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        con = koneksi.getConnection();
        try {
            //File file = new File("src/Ireport/Rpengadaan.jrxml");
            //File f2 = new File("src/Ireport/sis.jrxml");
            InputStream file1 = getClass().getResourceAsStream("/Ireport/user1.jrxml");
            JasDes = JRXmlLoader.load(file1);
            param.clear();
            JasRep =JasperCompileManager.compileReport(JasDes);
            JasPri = JasperFillManager.fillReport(JasRep, param,con);
            JasperViewer.viewReport(JasPri,false);
        } catch (JRException e) {
            //JOptionPane.showMessageDialog(null, "Maaf password atau username anda salah");
            //Logger.getLogger(Utama.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Utama().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Guru;
    private javax.swing.JMenuItem User;
    private javax.swing.JPanel bg;
    private javax.swing.JMenu data;
    private javax.swing.JMenu file;
    private javax.swing.JMenuItem instansi;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JInternalFrame login;
    private javax.swing.JMenu marketing;
    private javax.swing.JMenuItem mitra;
    private javax.swing.JPasswordField pass;
    private javax.swing.JMenu report;
    private javax.swing.JMenuItem sekolah;
    private javax.swing.JMenuItem siswa;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables

}